export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Hero } from './Hero'
export { default as Skills } from './Skills'
export { default as Works } from './Works'
export { default as Testimonials } from './Testimonials'